branch-defaults:
  default:
    environment: django-env7
environment-defaults:
  django-env3:
    branch: null
    repository: null
  django-env4:
    branch: null
    repository: null
  django-env5:
    branch: null
    repository: null
  django-env7:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
