# Generated by Django 2.1.1 on 2019-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('lon', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
